version: '3'
# volumes:
#   airflow-dags:
#     name: airflow-dags
#   airflow-logs:
#     name: airflow-logs

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    # volumes:
    #   - airflow-dags:/opt/airflow/dags
    #   - airflow-logs:/opt/airflow/logs
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  # airflow:
  #   image: apache/airflow:2.2.0
  #   ports:
  #     - ${AIRFLOW_PORT}:8081
  #   env_file:
  #     - .env
  #   environment:
  #     - AIRFLOW_HOME=${AIRFLOW_HOME}
  #     - FERNET_KEY=hjaskdfhjadkshfjakshd
  #     - EXECUTOR=LocalExecutor
  #   depends_on:
  #     - db
  #   volumes:
  #     - airflow-dags:/opt/airflow/dags
  #     - airflow-logs:/opt/airflow/logs
