# Use an official Python runtime as a parent image
FROM python:3.10.12-slim-bullseye

# Set the working directory in the container to /app
WORKDIR /app

# Add the current directory contents into the container at /app
ADD . /app

# Set PYTHONPATH to /app so that Python can find the src module
ENV PYTHONPATH=/app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Add wait-for-it script
RUN apt-get update && apt-get install -y wait-for-it

# Wait for the database to be ready before starting the API
CMD wait-for-it db:5432 --timeout=60 -- python src/apis/winetariffs_api.py
