version: '3'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    command: python src/db_setup.py    # && python src/apis/winetariffs_api.py

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

